# Generated by Django 3.1.1 on 2020-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200918_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(default=2, max_length=10, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
